name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py37_0
  - alabaster=0.7.12=py37_0
  - asn1crypto=1.3.0=py37_0
  - astor=0.8.0=py37_0
  - astroid=2.3.3=py37_0
  - attrs=19.3.0=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bokeh=2.0.1=py37hc8dfbb8_0
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.4.5.1=hecc5488_0
  - caiman=1.8.3=py37h0da4684_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.13.2=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - cloudpickle=1.2.2=py_0
  - cryptography=2.8=py37h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask-core=2.9.2=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.2=py37hc8dfbb8_1
  - giflib=5.2.1=h516909a_1
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.6.5=hd3a4fd2_1002
  - google-pasta=0.1.8=py_0
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=2.4.0=h37c48d4_1
  - hdf5=1.10.4=hb1b8bf9_0
  - hdmf=1.6.1=py_0
  - holoviews=1.13.2=pyh9f0ad1d_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - imageio=2.6.1=py37_0
  - imagesize=1.2.0=py_0
  - importlib_metadata=1.3.0=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.3=py37h39e3cac_1
  - ipyparallel=6.3.0=py37hc8dfbb8_0
  - ipython=7.11.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.15.2=py37_0
  - jeepney=0.4.2=py_0
  - jinja2=2.10.3=py_0
  - joblib=0.15.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.1=py37_0
  - keras-applications=1.0.8=py_0
  - keyring=20.0.0=py37_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - lame=3.100=h14c3975_1001
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_mkl
  - liblapacke=3.8.0=14_mkl
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.1=py37h5429711_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - more-itertools=8.0.2=py_0
  - mypy=0.770=py_0
  - mypy_extensions=0.4.3=py37hc8dfbb8_1
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_0
  - nose=1.3.7=py37hc8dfbb8_1004
  - notebook=6.0.3=py37hc8dfbb8_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_0
  - numpydoc=0.9.2=py_0
  - olefile=0.46=py37_0
  - opencv=4.1.0=py37h5517eff_4
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1g=h516909a_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.0=py_0
  - pandas=1.0.3=py37h0da4684_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - panel=0.9.5=py_1
  - param=1.9.3=py_0
  - parso=0.5.2=py_0
  - pcre=8.43=he6710b0_0
  - peakutils=1.3.3=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pims=0.4.1=py_1
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - protobuf=3.11.2=py37he6710b0_0
  - psutil=5.6.7=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.19=py37_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.5.2=py_0
  - pylint=2.4.4=py37_0
  - pynwb=1.3.0=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyqtgraph=0.11.0rc0=py_0
  - pyrsistent=0.15.6=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyviz_comms=0.7.4=pyh8c360ce_0
  - pywavelets=1.1.1=py37h7b6447c_0
  - pyzmq=18.1.0=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=0.6.0=py_0
  - qtconsole=4.6.0=py_1
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_1
  - rope=0.14.0=py_0
  - ruamel.yaml=0.16.6=py37h8f50634_1
  - ruamel.yaml.clib=0.2.0=py37h8f50634_1
  - scikit-image=0.15.0=py37he6710b0_0
  - scikit-learn=0.23.0=py37h8a51577_0
  - secretstorage=3.1.1=py37_0
  - send2trash=1.5.0=py_0
  - setuptools=44.0.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.13.0=py37_0
  - slicerator=1.0.0=py_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=2.3.1=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - spyder=3.3.6=py37_0
  - spyder-kernels=0.5.2=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorflow=2.0.0=gpu_py37h768510d_0
  - tensorflow-base=2.0.0=gpu_py37h0ec5d1f_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.0.0=pyh5ca1d4c_0
  - tifffile=0.15.1=py37hc1659b7_1001
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.46.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py37_0
  - typed-ast=1.4.1=py37h516909a_0
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.7=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - wurlitzer=2.0.0=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.4=h516909a_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - astunparse==1.6.3
    - cachetools==4.1.0
    - gast==0.3.3
    - google-auth==1.14.3
    - google-auth-oauthlib==0.4.1
    - grpcio==1.29.0
    - h5py==2.10.0
    - keras==2.3.1
    - keras-preprocessing==1.1.2
    - memory-profiler==0.57.0
    - oauthlib==3.1.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==5.3.1
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scipy==1.4.1
    - tb-nightly==2.3.0a20200521
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow-addons==0.10.0
    - tensorflow-estimator==2.2.0
    - tensorflow-gpu==2.2.0
    - tf-estimator-nightly==2.3.0.dev2020052101
    - typeguard==2.7.1
prefix: /home/nellab/anaconda3/envs/tf2

